apiVersion: v1
kind: Secret
metadata:
  name: keda-secret
  namespace: demo-namespace
data:
  host: aHR0cDovL2V4YW1wbGUtaG9zdA==   # Base64-encoded URL

---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-authentication
  namespace: demo-namespace
spec:
  secretTargetRef:
  - parameter: host
    name: keda-secret
    key: host

---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: keda-scaled-object-podname
  namespace: demo-namespace
  annotations:
    autoscaling.keda.sh/paused: "false"
spec:
  scaleTargetRef:
    kind: Deployment
    name: deployment-name
  minReplicaCount: 1
  maxReplicaCount: 10
  idleReplicaCount: 0
  cooldownPeriod: 300
  pollingInterval: 1
  triggers:
  - type: rabbitmq
    metadata:
      protocol: http
      queueName: rabbitmq-queue-name
      vhostName: /
      mode: QueueLength
      value: "1"
    authenticationRef:
      name: keda-trigger-authentication
